resource "local_file" "inventory" {
  content  = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nginx]
    ${terraform.workspace == "stage" ? "stage." : ""}literis.ru ansible_host=${local.public_ip[terraform.workspace]} ansible_user=ubuntu

    [mysql]
    db01.literis.ru ansible_host=${yandex_compute_instance.db01.network_interface.0.ip_address} ansible_user=ubuntu
    db02.literis.ru ansible_host=${yandex_compute_instance.db02.network_interface.0.ip_address} ansible_user=ubuntu

    [wordpress]
    app.literis.ru ansible_host=${yandex_compute_instance.app.network_interface.0.ip_address} ansible_user=ubuntu

    [gitlab]
    gitlab.literis.ru ansible_host=${yandex_compute_instance.gitlab.network_interface.0.ip_address} ansible_user=ubuntu

    [runner]
    runner.literis.ru ansible_host=${yandex_compute_instance.runner.network_interface.0.ip_address} ansible_user=ubuntu

    [monitoring]
    monitoring.literis.ru ansible_host=${yandex_compute_instance.monitoring.network_interface.0.ip_address} ansible_user=ubuntu

    [nodes:children]
    mysql
    wordpress
    gitlab
    runner
    monitoring

    [nodes:vars]
    ansible_ssh_common_args= "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"
    DOC
  filename = "../ansible/inventory"
}