resource "local_file" "inventory" {
  content  = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nginx]
    ${terraform.workspace == "stage" ? "stage." : ""}literis.ru ansible_host=${local.public_ip[terraform.workspace]} ansible_user=ubuntu

    [mysql]
    db01.literis.ru ansible_host=${yandex_compute_instance.db01.network_interface.0.ip_address} ansible_user=ubuntu
    db02.literis.ru ansible_host=${yandex_compute_instance.db02.network_interface.0.ip_address} ansible_user=ubuntu

    [wordpress]
    www.literis.ru ansible_host=${yandex_compute_instance.www.network_interface.0.ip_address} ansible_user=ubuntu

    [nodes:children]
    mysql
    wordpress

    [nodes:vars]
    ansible_ssh_common_args= "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"
    DOC
  filename = "../ansible/inventory"
}