version: '3.8'

services:
  elasticsearch:
    build:
      dockerfile: Dockerfile
    image: ubuntu-python
    container_name: elastic
    restart: always
    command: "sleep 6000000"

  kibana:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu-python
    container_name: kibana
    restart: always
    command: "sleep 6000000"