---
- hosts: nginx
  become: yes
  roles:
    - letsencrypt
    - node-exporter
  tags:
    - certbot

- hosts: nginx
  become: yes
  roles:
    - nginx
    - node-exporter
  tags:
    - nginx

- hosts: mysql
  become: yes
  roles:
    - geerlingguy.mysql
    - node-exporter
  tags:
    - mysql

- hosts: wordpress
  become: yes
  roles:
    - wordpress
    - node-exporter
  tags:
    - wordpress

- hosts: gitlab
  become: yes
  roles:
    - geerlingguy.gitlab
    - node-exporter
  tags:
    - gitlab

- hosts: monitoring
  become: yes
  roles:
    - prometheus
    - alertmanager
    - node-exporter
    - grafana
  tags:
    - monitoring